### ISSUE TITLE
ModuleNotFoundError: No module named 'gym_macro_overcooked'

### ISSUE THREAD

**Issue by PulkitRustagi** [yuchen-x/MacroMARL#1]
I am trying to run the overcooked demo in `visualization/test_overcooked_ma.py` but the `MacEnvWrapper`, imported from the `gym_macro_overcooked`, does not exist as a package or script

**Comment by wwlin1198** [comment]
https://github.com/WeihaoTan/gym-macro-overcooked

(new student of Chris)

**Comment by yuchen-x** [comment]
@PulkitRustagi I am really sorry for my very late reply. Thank you for your interest in the work. Please let me know if you have any further questions! 

@wwlin1198 Thank you so much for helping with the response!
